# EEA jupyter notebook for data science in python
# Example docker-compose file
# to secure the Notebook server with a custom password hashed using 
# IPython.lib.passwd() instead of the default token and add it in
# the command --NotebookApp.password=

notebook:
  environment:
  - NB_UID=1001
  ports:
  - "8800:8888"
  user: root
  volumes:
  - /path/to/jupyterdata:/home/jovyan/work:z
  labels:
    io.rancher.scheduler.affinity:host_label: datascience-demarant=yes
    io.rancher.container.hostname_override: container_name
  image: eeacms/notebook:latest
  command: start-notebook.sh --NotebookApp.password='sha1:your_hashed_password'
  